{
 "title": "Hue",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Licht eingeschaltet (Aus/Teilweise/Alle)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hue_group_on{name!=\"Wohnbereich\", name!=\"Zuhause\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Esstisch reachability",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hue_light_reachable{name=\"Esstisch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scraping failure count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hue_sensor_scrapes_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Siematic Lights On",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "hue_light_on{manufacturer_name=\"LS Deutschland GmbH\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}